name = "shorter"
main = "src/worker.js"
compatibility_date = "2023-06-04"

kv_namespaces = [{binding = "shorter", id = "b53da68bdb714f29a2c69eaf756756aa" }]
routes = [{pattern = "url.n25tech.com", zone_name = "n25tech.com", custom_domain = true}]

#secret vars: SHORTER_BASIC_USER, SHORTER_BASIC_PASSWORD, SHORTER_ROOT_DOMAIN

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
#[[kv_namespaces]]
#binding = "shorter"
#id = "b53da68bdb714f29a2c69eaf756756aa"
#binding = "shorter_config"
#id = "49358ef627fa4ea18fa5c656d263542e"

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # Bucket binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv#bucket
# [[buckets]]
# binding = "MY_BUCKET"
# name = "my-bucket"
# bucket_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"
